### ISSUE TITLE
Code_for_hacktoberfest!

### ISSUE THREAD

**Issue by afred-khan** [aliya-rahmani/-HACKTOBERFEST2K20#1]
Make a pull request of whatever apps, games, html pages, code you have written for hacktoberfest.

**Comment by Shivam4747** [comment]
hey afred khan, I want to make a PR of my code of my little game i created in python!
Can you help me out?!

**Comment by sneha-mehta** [comment]
hey... I want to make a PR of magic number code in python. So if u can help me!

**Comment by shiyan99s** [comment]
Hey,
I want to make a PR on Depth First Search and Depth for Search for Graphs in python because there's room for that in your -HACKTOBERFEST2K20/Python/

**Comment by Jayanth19524** [comment]
I  want to make a simple portfolio website for myself. can I include that?

**Comment by afred-khan** [comment]
@Jayanth19524  Sure, you can

**Comment by anupamishra333** [comment]
HEY...!!!!! i just want to make PR of Snake Water Gun game .  Can You please see and if you can add. :)

**Comment by rupesh48** [comment]
Hey! @afred-khan  I want to make a PR of DS algo questions in python. So if you can help me!

**Comment by WxBarbosa** [comment]
I want to make a PR of my covid application. So if you can help me!

**Comment by VishalAmbavade** [comment]
I want to make a PR for `Sudoku solver`. Can I do that?

**Comment by sumasreeeduru** [comment]
Hi, I want to make a PR for a website.Can I do it?

**Comment by afred-khan** [comment]
@VishalAmbavade @sumasreeeduru You can make a PR on any topic, go ahead!

**Comment by Rohanfizz** [comment]
i want to upload some linkedlist questions can i do that?

**Comment by shubhamc1200** [comment]
Hey, can I make a pr of Searching Algos(Binary ,Linear) in python??

**Comment by shubhamc1200** [comment]
Hey ! I wanted to add basic blog using django python

**Comment by Srithanya** [comment]
Hi can I make PR on Twitter Bot which I have done?

**Comment by Red-0111** [comment]
I have made a pac man game please checkout

**Comment by C15C01337** [comment]
Wow

**Comment by demaria11** [comment]
Tried Hangman simple code

**Comment by Shreyas12345678** [comment]
I have created music app using javascript can I add it here?

**Comment by aritrochakraborty29** [comment]
I want to add some cool games based on JavaScript
can you please assign me..?

**Comment by Anupam-Panwar** [comment]
Hello @afred-khan 
I have seen that there is no program for insertion sort in the C folder
I would like to add this program in this folder
so can you assign this to me

**Comment by Anupam-Panwar** [comment]
Hello @afred-khan 
I would like to add programs of link list and it's operation in C folder
Can you please assign this task to me??

**Comment by afred-khan** [comment]
@aritrochakraborty29 @Anupam-Panwar No need to get assigned for PRs, just add them.

**Comment by rishit-khandelwal** [comment]
can I add [my app](https://covid-app-9f82e.web.app/) I made for covid19 statistics.

**Comment by AmreshSinha** [comment]
Where can I add my PHP Script ?

**Comment by subhadeep-123** [comment]
I want to add a Database Application in C, I checked that you do not have anything much other than Algorithms in C

**Comment by rishit-khandelwal** [comment]
Can I organize the code by language, because a lot of code belonging to the same language is in different folders and I feel that it should be in the following structure:
```
README.md
...
JavaScript
      |
      ----- folder1
      ----- folder 2
Python
     |
     ----- folder 3
     ----- folder4
```
In this each folder there is a different project so there wouldn't be a mixup of code and other problems.

**Comment by rishit-khandelwal** [comment]
I have done this and made a pull request

**Comment by chhipashubham970** [comment]
Hey, I want to make PR my Automated Folder Cleaner program.
