### ISSUE TITLE
Regarding projects apps

### ISSUE THREAD

**Issue by shubhamc1200** [aliya-rahmani/-HACKTOBERFEST2K20#106]
Ideally, we can have 8 main folders: JAVA, PYTHON, C, C++, C#, Go, HTML, RUST. 
and inside each main folder let's make a new folder called "Projects" for projects like games, apps, etc.  to make it look more organized and presentable.

**Comment by amitoj-singh** [comment]
can I do it?

**Comment by afred-khan** [comment]
@amitoj-singh Do the sorting part and put the respective projects in their folder

**Comment by shubhamc1200** [comment]
@afred-khan I posted it so  I should do this task right??

**Comment by amitoj-singh** [comment]
> @amitoj-singh Do the sorting part and put the respective projects in their folder

I think @afred-khan wants to take up this issue. If He can do it then I think he'll manage🙂

Good luck.

**Comment by shubhamc1200** [comment]
@amitoj-singh  buddy he assigned you apparently

**Comment by shubhamc1200** [comment]
I can manage it since I came up with the issue .

**Comment by afred-khan** [comment]
@shubhamc1200 It's great if you want to sort this issue, go ahead!

**Comment by shubhamc1200** [comment]
Thanks!! @afred-khan
