### ISSUE TITLE
Submit Projects in PYthon

### ISSUE THREAD

**Issue by afred-khan** [aliya-rahmani/-HACKTOBERFEST2K20#2]

**Comment by Nikzy7** [comment]
I have an OpenCV python based text detection project. If you could assign this to me ?

**Comment by vaderjunior** [comment]
Hey,
I have a twitter bot.
Can you assign this to me?

**Comment by zjc9022** [comment]
I have a few projects I'd like to add. Can you assign me?

**Comment by afred-khan** [comment]
@zjc9022 Just submit the PR's you don't need to get assigned for those.

**Comment by KushGrandhi** [comment]
@afred-khan submitted a PR of fashionmnist #95

**Comment by aritrochakraborty29** [comment]
I want to add some Python based project..
can you please assign me..?

**Comment by Red-0111** [comment]
made flappy bird game in python please review

**Comment by Red-0111** [comment]
made tron classical game pls review

**Comment by Shreyas12345678** [comment]
I want to add pyhton based tkinter, game can I add it ?

**Comment by skshahnawaz** [comment]
@afred-khan Please review and merge #198 . Its a implementation of real time blink detection using Python and OpenCV
