### ISSUE TITLE
Code anything in C++

### ISSUE THREAD

**Issue by afred-khan** [aliya-rahmani/-HACKTOBERFEST2K20#3]

**Comment by skshahnawaz** [comment]
#68 Implementation of kosarjus algorithm in c++

**Comment by neeladriOO7** [comment]
Added C++ code for AVL Tree implementation #71

**Comment by skshahnawaz** [comment]
Added Kruskals algorithm in c++ #69

**Comment by skshahnawaz** [comment]
Maximum Heap Implementation in c++ #70

**Comment by rahulvermafreelancer** [comment]
Hello, can i add some programs? i want to contribute.

**Comment by Mithunitp** [comment]
I have created Fibonacci series using recursion in C . Requesting review.

**Comment by Zualemo-xo** [comment]
I have added a program to perform insertion and deletion at head ,middle and tail elements respectively on a linked list. Implemented in C++. Pr #113

**Comment by kartikeyaGUPTA45** [comment]
@afred-khan please assign me binary and linear search in C++

**Comment by kartikeyaGUPTA45** [comment]
@afred-khan  please assign me the following programs in c++
1) Equilibrium Point in Array
2) Fibonacci series using Binet's Theorem
3) Saddle Points in 2D Array

**Comment by rgarg-2711** [comment]
adding binary search and LIS in c++

**Comment by meteora2002** [comment]
please assign to me this 266A - Stones on the Table problem of leet code

**Comment by meteora2002** [comment]
@afred-khan please assign to me this 266A - Stones on the Table problem of leet code

**Comment by afred-khan** [comment]
@meteora2002  @kartikeyaGUPTA45 You don't need to get assigned for the PRs, just do it.

**Comment by Abdulrahmannaser** [comment]
Added adhoc and math codes #232

**Comment by debajitdeb11** [comment]
@afred-khan I have added some Important Algorithms in C++ and created a PR #274 but there are some conflicts please kindly have a look.
Thanks!

**Comment by Jeewantha95** [comment]
Hi, I would like to work on this feature. Please assign it to me.

**Comment by Ashutoshnegi880** [comment]
I would like to code a Fibonacci series in c++

**Comment by aniket173000** [comment]
I HAVE MADE A PR IN WHICH I HAVE ADDED SOLUTION CODE IN C LANGUAGE FOR FINDING MAXIMUM SUBARRAY SUM IN CIRCULAR ARRAY SO PLEASE REVIEW IT AND MERGE IT.
