### ISSUE TITLE
Add some PRs in Ruby, C and other languages too

### ISSUE THREAD

**Issue by afred-khan** [aliya-rahmani/-HACKTOBERFEST2K20#4]

**Comment by Nikzy7** [comment]
I have a lot of programs in c, java, python, c++ etc. Can you assign this to me?

**Comment by afred-khan** [comment]
@Nikzy7 You don't need to get assigned for the PRs, just do it.

**Comment by Nikzy7** [comment]
check my PR #7 . Happy Hacktoberfest !

**Comment by kartikeyaGUPTA45** [comment]
@afred-khan  please assign me the calculator program in rust language
